name: infinite_horizons
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Make an animated circular countdown 
  circular_countdown_timer: ^0.2.3
  # Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  # Internationalization (Easy translations)
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.2.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
